GET http://localhost:3001/api/v1/cart/6529344b60eeb2ae81ba72b0

### Use discount
GET http://localhost:3001/api/v1/cart/discount
content-type: application/json

{
    "discount_code": "code-123",
    "user_id": "6531174454986d0cfa0cddbc",
    "total": 200000
}

### Update cart item
POST http://localhost:3001/api/v1/cart/6529344b60eeb2ae81ba72b0
content-type: application/json

{
    "inventory": 1,
    "product_id": "652d3a71568c1e844f295b2c",
    "variation": "normal",
    "quantity": 11,
    "price": 2000
}

### Delete item in cart
POST http://localhost:3001/api/v1/cart/delete/6529344b60eeb2ae81ba72b0
content-type: application/json

{
    "product_id": "1",
    "variation": "normal"
}

### Delete all items in cart
POST http://localhost:3001/api/v1/cart/deleteAll/6529344b60eeb2ae81ba72b0