GET http://localhost:3001/api/v1/carts/65b68c534aeec67d1fcf1720

### Update cart item
POST http://localhost:3001/api/v1/carts/update/656dda8c80d2bc76a5a4f07f
content-type: application/json

{
    "product_id": "655d5020c53cf61a9718fa50",
    "variation_id": "6569df1dfd94347d9e7c740a",
    "quantity": 2,
    "price": 2000
}

### Delete item in cart
POST  http://137.184.232.94/api/v1/carts/item/6572b176b34b8805e84d6c8b
content-type: application/json

{
    "product_id": "65759ccdb285b46cadf872dd",
    "variation": null
}

### Delete all items in cart
POST http://localhost:3001/api/v1/carts/items/6529344b60eeb2ae81ba72b0