GET http://localhost:3001/api/v1/category/getCategories

### Get parent categories
GET http://localhost:3001/api/v1/category/parentCategories

### Get category by ID
GET http://localhost:3001/api/v1/category/id/6543a5b64ecb76b243b6f48b

### Search category
GET http://localhost:3001/api/v1/category/search?search=asdasd

### Create category
POST http://localhost:3001/api/v1/category
content-type: application/json

{
    "title": "Category 4",
    "description": "Category 4",
    "thumbnail": "https://images.unsplash.com/photo-1698414392317-2697b2e276e4?auto=format&fit=crop&q=80&w=1935&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "parent_id": "653e595db3ad8d738fef0ce4"
}


### Update category
PATCH http://localhost:3001/api/v1/category/653cf39bfadd38d2f7d75c64
content-type: application/json

{
    "public": true
}

### Delete category
POST http://localhost:3001/api/v1/category/6533c0bd6e2264a5e10388bd
content-type: application/json

{
    "parent_id": "6533c0bd6e2264a5e10388bd"
}