### get discounts
GET http://localhost:3001/api/v1/discounts
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzExNzQ0NTQ5ODZkMGNmYTBjZGRiYyIsImlhdCI6MTY5Nzg5MjEyOSwiZXhwIjoxNjk3ODkyMTg5fQ.bZbDeaF_c-MeHqEhiKZBtY92fwZGZfHllJ6s6J-SxZo
public-key: Key 228c718f-ea0b-4916-9c5e-086a5f9b4bd6

### get discount
GET http://localhost:3001/api/v1/discounts/code-123

### search discount
GET http://localhost:3001/api/v1/discounts/search?search=code-test

### Create discount
POST http://localhost:3001/api/v1/discounts
content-type: application/json

{
    "discount_name": "discount 4",
    "discount_code": "code-123",
    "discount_applies": "all",
    "discount_type": "percentage",
    "discount_value": 10,
    "discount_start_date": "2023-10-20T12:07:33.023Z",
    "discount_end_date": "2023-10-21T12:07:33.023Z",
    "discount_max_uses": 2,
    "discount_per_user": 3,
    "discount_min_value": 0
}

### Update discount
PATCH  http://localhost:3001/api/v1/discounts/653123132dcd011b61aa3681
content-type: application/json

{
 "discount_start_date": "2023-9-28",
 "discount_end_date": "2023-12-28"
}