### get discounts
GET http://localhost:3001/api/v1/discounts
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmRkYThjODBkMmJjNzZhNWE0ZjA3ZiIsImlhdCI6MTcwMTgzMTg0MiwiZXhwIjoxNzAxOTE4MjQyfQ.1zPomG3qoCN4Fl94UPgVp1K4zd85No6_E59S-o7ZWc8
public-key: Key fa44e80a-3e74-4b8b-8c55-620e011e3576
x-api-key: Key 1e818a62-4000-4af1-b978-26b89c374462

### get discount
GET http://localhost:3001/api/v1/discounts/ASDASd
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmRkYThjODBkMmJjNzZhNWE0ZjA3ZiIsImlhdCI6MTcwMTgzMTg0MiwiZXhwIjoxNzAxOTE4MjQyfQ.1zPomG3qoCN4Fl94UPgVp1K4zd85No6_E59S-o7ZWc8
public-key: Key fa44e80a-3e74-4b8b-8c55-620e011e3576
x-api-key: Key 1e818a62-4000-4af1-b978-26b89c374462

### search discount
GET http://localhost:3001/api/v1/discounts/search?search=code-test

### Create discount
POST http://localhost:3001/api/v1/discounts
content-type: application/json

{
    "discount_name": "Summer",
    "discount_code": "SUMMERS",
    "discount_applies": "all",
    "discount_type": "percentage",
    "discount_value": 100,
    "discount_start_date": "2024-02-10T12:07:33.023Z",
    "discount_end_date": "2024-02-20T12:07:33.023Z",
    "discount_max_uses": 100,
    "discount_per_user": 10,
    "discount_min_value": 0
}

### Update discount
PATCH  http://localhost:3001/api/v1/discounts/653123132dcd011b61aa3681
content-type: application/json

{
 "discount_start_date": "2023-9-28",
 "discount_end_date": "2023-12-28"
}

### Use discount
POST http://localhost:3001/api/v1/discounts/use
content-type: application/json

{
    "discount_code": "SUMMER-1234",
    "user_id": "656dda8c80d2bc76a5a4f07f",
    "total": 179000
}