### Get orders
GET http://localhost:3001/api/v1/orders

### Get order
GET http://localhost:3001/api/v1/orders/650a5fc7cf7feba3b1e455de

### Search order
GET http://localhost:3001/api/v1/order/search?search=Antran+dev


### Create order
POST http://localhost:3001/api/v1/orders
content-type: application/json

{
    "user_infor": {
        "email": "phamtrangiaan27@gmail.com",
        "name": "Antran dev",
        "address": "55 Nguyễn Kiệm, Phường 3, Quận Gò Vấp, TP.Hồ Chí Minh",
        "phoneNumber": "0946003423"
    },
    "items": [
        {
            "_id": "6569df1dfd94347d9e7c7410",
            "product_id": "655d5020c53cf61a9718fa50",
            "name": "Apple iPhone 15 Pro",
            "thumbnail": "http://localhost:3001/uploads/product/1700833232193Screenshot 2023-10-19 161718.png",
            "options": ["Red", "XL"],
            "promotion_price": 0,
            "price": 200,
            "quantity": 3,
            "link": "#"
        }
    ],
    "shipping_cost": 0,
    "sub_total": 600,
    "total": 600,
    "status": "pending",
    "discount_codes": [],
    "payment_method": "cash"
}