GET http://localhost:3001/api/v1/products

### Get product by category_id
GET http://localhost:3001/api/v1/products/category/654446d696123fda4c00d7ff?color=Red

### Get product by id
GET http://localhost:3001/api/v1/products/id/655df956a5123e38b7383964

### Get product by slug
GET http://localhost:3001/api/v1/products/asdtest

### Create product
POST http://localhost:3001/api/v1/products
content-type: application/json

{
    "category": "65203e8b731fb60dfc68f5ae",
    "title": "product tao inventory",
    "shortDescription": "zxc",
    "description": "as",
    "thumbnail": "http://localhost:3001/uploads\\product\\1689511560274.png",
    "options": [
        {
            "code": "color",
            "name": "Màu sắc",
            "values": [
                {
                    "label": "Đỏ"
                },
                {
                    "label": "Xanh"
                },
                {
                    "label": "Vàng"
                }
            ]
        },
        {
            "code": "size",
            "name": "Kích thước",
            "values": [
                {
                    "label": "S"
                },
                {
                    "label": "M"
                },
                {
                    "label": "L"
                }
            ]
        }
    ],
    "price": 2000,
    "inventory": 10
}

### Update product
PATCH  http://localhost:3001/api/v1/products/652154c58b9bca17bcd2237e
content-type: application/json

{
    "title": "product test6 updated"
}

### Search product
GET http://localhost:3001/api/v1/products/search?search=inventory
### Upload thumbail
PATCH http://localhost:3001/api/v1/products/649d9a30fd1f9aed9db239f4
content-type: application/json

{
    "title": "Architecture Art Lorem2",
    "description": "Updated description"
}

### Delete product
POST http://localhost:3001/api/v1/products/64b3e67dcd9c65d631efb095