### Get users
GET  http://localhost:3001/api/v1/user/getUsers
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzExNzQ0NTQ5ODZkMGNmYTBjZGRiYyIsImlhdCI6MTY5OTE2NzY4NCwiZXhwIjoxNjk5MTY3NzQ0fQ.gl2KQEOEjToSSqWLvK4QVsz8tzoQmrovN5pRgk6Y5OM
public-key: Key 56665beb-1966-4e59-865c-026e5b76bc20
content-type: application/json

### Get user
GET  http://localhost:3001/api/v1/user/6523fe7d3012f7b84181c67c

### Get user by email
GET  http://localhost:3001/api/v1/user/6523fe7d3012f7b84181c67c

### Send confirm email
POST  http://localhost:3001/api/v1/user/send/confirmEmail
content-type: application/json

{
    "name": "Antrandev",
    "email": "phamtrangiaan27@gmail.com",
    "password": "cunyeu1506"
}

### Send confirm change password
POST  http://localhost:3001/api/v1/user/send/changePassword
content-type: application/json

{
    "email": "phamtrangiaan27@gmail.com"
}

### Create user
POST  http://localhost:3001/api/v1/users
content-type: application/json

{
    "name": "Antrandev",
    "email": "phamtrangiaan27@gmail.com",
    "password": "$2b$10$ghjllp97RPLb.9wZz1AM8uPbT7ll5owHrh5ZUbEiRUp/dYdRq5fsa"
}

### login
POST  http://localhost:3001/api/v1/users/login
content-type: application/json

{
    "email": "phamtrangiaan27@gmail.com",
    "password": "cunyeu1506"
}

### refresh token
POST  http://localhost:3001/api/v1/user/refreshToken
content-type: application/json

 {
    "id": "6531174454986d0cfa0cddbc",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MzExNzQ0NTQ5ODZkMGNmYTBjZGRiYyIsImlhdCI6MTY5OTE2NzU3MiwiZXhwIjoxNzE0NzE5NTcyfQ.KTmxwkQeJ0Zr063nyD6JKAXPOHeGa6DDNXV2sWVHDiw"
 }

### ban user
POST  http://localhost:3001/api/v1/user/ban
content-type: application/json

{
    "user_id": "6523fe7d3012f7b84181c67c"
}

### unban user
POST  http://localhost:3001/api/v1/user/unban
content-type: application/json

{
    "user_id": "6523fe7d3012f7b84181c67c"
}