### Get users
GET  http://localhost:3001/api/v1/user/getUsers

### Get user
GET  http://localhost:3001/api/v1/user/6523fe7d3012f7b84181c67c

### Get user by email
GET  http://localhost:3001/api/v1/user/6523fe7d3012f7b84181c67c

### Send confirm email
POST  http://localhost:3001/api/v1/user/sendConfirmEmail
content-type: application/json

{
    "name": "Antrandev",
    "email": "phamtrangiaan27@gmail.com",
    "password": "cunyeu1506"
}

### Create user
POST  http://localhost:3001/api/v1/user
content-type: application/json

{
    "name": "Antrandev",
    "email": "phamtrangiaan27@gmail.com",
    "password": "$2b$10$9oxdtpqbXq6gbsS1KdC03ur1iysNxSusEmvRj22O886hsmifMsQGe"
}

### login
POST  http://localhost:3001/api/v1/user/login
content-type: application/json

{
    "email": "phamtrangiaan27@gmail.com",
    "password": "cunyeu1506"
}

### refresh token
POST  http://localhost:3001/api/v1/user/refreshToken
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MjkzNDRiNjBlZWIyYWU4MWJhNzJiMCIsImlhdCI6MTY5NzE5OTI2MiwiZXhwIjoxNjk3MTk5MzIyfQ.4FOfg88Rfd1JVXutDB_3dPIZgWQGA590Viwv6NPYYSA
public-key: Key 14b3daf6-4aa8-4cbc-9c03-735353cf20d3
content-type: application/json

### ban user
POST  http://localhost:3001/api/v1/user/ban
content-type: application/json

{
    "user_id": "6523fe7d3012f7b84181c67c"
}

### unban user
POST  http://localhost:3001/api/v1/user/unban
content-type: application/json

{
    "user_id": "6523fe7d3012f7b84181c67c"
}