### Get users
GET  http://localhost:3001/api/v1/user/getUsers

### Get user
GET  http://localhost:3001/api/v1/user/6523fe7d3012f7b84181c67c

### Get user by email
GET  http://localhost:3001/api/v1/user/6523fe7d3012f7b84181c67c

### Send confirm email
POST  http://localhost:3001/api/v1/user/sendConfirmEmail
content-type: application/json

{
    "name": "Antrandev",
    "email": "phamtrangiaan27@gmail.com",
    "password": "cunyeu1506"
}

### Create user
POST  http://localhost:3001/api/v1/user
content-type: application/json

{
    "name": "Antrandev",
    "email": "phamtrangiaan27@gmail.com",
    "password": "$2b$10$9oxdtpqbXq6gbsS1KdC03ur1iysNxSusEmvRj22O886hsmifMsQGe"
}

### login
POST  http://localhost:3001/api/v1/user/login
content-type: application/json

{
    "email": "phamtrangiaan27@gmail.com",
    "password": "cunyeu1506"
}

### refresh token
POST  http://localhost:3001/api/v1/user/refreshToken
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MjNmZTdkMzAxMmY3Yjg0MTgxYzY3YyIsImlhdCI6MTY5Njk0NDc1OCwiZXhwIjoxNjk3MDMxMTU4fQ.esLM3IYcAqY9wkChhafJ_d8ptJuu2FmUfzEontT1HYw
public-key: Key 3fc05829-5ef8-4c24-b548-f910c35b6ffc
content-type: application/json